### PR TITLE
Enforce Contract in `AddBalance`

### PR DESCRIPTION
**Pull request by RodrigoVillar**
This PR updates `AddBalance()` in MorpheusVM so that, if an account doesn't exist and if it wasn't given permission to create an account, that it returns an error. This PR also updates the documentation of `AddBalance()` to make it explicit that if the account doesn't exist and `createAccount = false`, it should return an error.

### CODE REVIEW

**Comment by aaronbuchwald** [comment]
What contract in the balance handler are you referring to? Do you just mean based on the name of the function?

**Comment by RodrigoVillar** [comment]
> What contract in the balance handler are you referring to? Do you just mean based on the name of the function?

Yes, the name/interface of the function is part of the contract. By naming the parameter `createAccount`, the contract that's implied is that:

- If the account doesn't exist, but `createAccount = true`, then create the account. Otherwise, I should return an error.

**Comment by RodrigoVillar** [comment]
Also want to add that by currently returning a no-op, this PR blocks #1693 as there's no way to test between setting `createAccount = true` and `createAccount = false`

**Comment by aaronbuchwald** [comment]
> > What contract in the balance handler are you referring to? Do you just mean based on the name of the function?
> 
> Yes, the name/interface of the function is part of the contract. By naming the parameter `createAccount`, the contract that's implied is that:
> 
> * If the account doesn't exist, but `createAccount = true`, then create the account. Otherwise, I should return an error.

I don't think that name explicitly specifies whether it should return an error or treat it as a no-op, so disagree on that point, but do think it makes sense to change the behavior to return an error and add a comment to the interface to specify that behavior.

**Comment by RodrigoVillar** [comment]
Closing in favor of removing the `createAccount` parameter entirely

**Pull request closed without merging**
