### PR TITLE
[executor] Simplify Logic + Speed Up Tests

### PR DESCRIPTION
**Pull request by patrick-ogrady**

### CODE REVIEW

**Comment by patrick-ogrady** [comment]
Failing:
```
--- FAIL: TestExecutorMultiConflict (0.11s)
    executor_test.go:162: 
        	Error Trace:	/home/runner/work/hypersdk/hypersdk/executor/executor_test.go:162
        	Error:      	Not equal: 
        	            	expected: []int{0, 10, 15, 20, 30, 40, 50, 60, 70, 80, 90}
        	            	actual  : []int{0, 15, 10, 20, 30, 40, 50, 60, 70, 80, 90}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -2,4 +2,4 @@
        	            	  (int) 0,
        	            	+ (int) 15,
        	            	  (int) 10,
        	            	- (int) 15,
        	            	  (int) 20,
        	Test:       	TestExecutorMultiConflict
FAIL
```

**Comment by patrick-ogrady** [comment]
Load tests are stuck on waiting for `executable` after all items enqueued...this means some item is getting dropped somewhere or that its dependencies weren't decremented.

**Comment by patrick-ogrady** [comment]
217 (in this run) is never executed:
```
dependencies remaining 217 1
dependencies remaining 218 1
queued 219
queued 220
queued 221
queued 222
queued 223
queued 224
queued 225
dependencies remaining 226 1
queued 227
queued 228
queued 229
queued 230
queued 231
queued 232
dependencies remaining 233 1
queued 234
queued 235
queued 236
queued 207
queued 237
queued 238
queued 239
queued 240
queued 241
queued 242
queued 243
queued 244
queued 245
queued 246
queued 247
queued 248
queued 249
queued 250
queued 251
queued 252
queued 253
queued 254
queued 255
queued 210
queued 109
queued 233
queued 218
queued 226
queued 152
```

**Comment by patrick-ogrady** [comment]
load test is failing with:
```
skipped 246 block full
skipped 247 block full
skipped 248 block full
skipped 244 block full
skipped 245 block full
base queued 249
base queued 250
base queued 251
skipped 221 block full
skipped 250 block full
skipped 251 block full
skipped 249 block full
base queued 252
base queued 253
base queued 254
base queued 255
skipped 253 block full
skipped 255 block full
skipped 254 block full
skipped 252 block full
```

**Review by wlawt — APPROVED** [review]

**Pull request merged**
