### PR TITLE
chore: fix symbol error

### PR DESCRIPTION
**Pull request by liangmulu**
fix symbol error

### CODE REVIEW

**Comment by aaronbuchwald** [comment]
Could you include a PR description as per https://github.com/ava-labs/hypersdk/blob/bd64ba5121e8d21a755b6c85a1ca71039d870d1d/CONTRIBUTING.md ?

**Review by richardpringle — DISMISSED** [review]

**Comment by richardpringle** [comment]
@liangmulu, the file was renamed (the work was in progress before the PR was opened). Should be easy to fix. Thanks for the contribution by the way

**Comment by liangmulu** [comment]
> @liangmulu, the file was renamed (the work was in progress before the PR was opened). Should be easy to fix. Thanks for the contribution by the way

Thanks. My pleasure.

**Comment by liangmulu** [comment]
> @liangmulu, the file was renamed (the work was in progress before the PR was opened). Should be easy to fix. Thanks for the contribution by the way

Thanks. Upstream and modified.

**Review by iFrostizz — APPROVED** [review]

**Review by aaronbuchwald — APPROVED** [review]

**Pull request merged**
